Fixed include path to cairo.h for OSX build
This was not affecting Linux env because gcc seems nicer there (e.g.
/usr/local/include is added by default to gcc include path).
On OSX, build error was:
../src/Canvas.h:19:10: fatal error: 'cairo/cairo.h' file not found
#include <cairo/cairo.h>
Other way to fix this is to remove “cairo/“ from both #include in
./src/Canvas.h and ./src/PNG.h